#Create environment using:
#$ conda env create --file=file-name.yml
#We assume the environment has a gpu.
# This environment is functional on windows.
name: mathjobs
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
- python=3.8
- pip=21
- jupyter==1.0.0
- pip:
  - beautifulsoup4==4.6.3
  - requests==2.25.1
  - matplotlib==3.1.2
  - html5lib==1.0.1
  - pandas==1.2.3
  - scikit-learn==0.24.1
  - flask==1.1.0
  - gunicorn==20.0.4
  - redis==3.4.1
  - rq==1.2.2